// Generated by CoffeeScript 1.3.3
/*
 * jQuery Hashtag, a light weight hashtag function binding
 * utility for jQuery with support for regular expressions.
 *
 * Written by Hans Kristian Flaatten for Turistforeningen,
 * http://www.turistforeningen.no
 *
 * Version 1.0.0
 * Full source at https://github.com/Turistforeningen/jQuery.Hashtag
 * Copyright (c) 2012 Turistforeningen @  http://www.turistforeningen.com
 *
 * MIT License, https://github.com/Turistforeningen/jQuery.Hashtag/blob/master/LICENSE.md
 *
*/(function(){"use strict";$(window).on("hashchange",function(){$(this).Hashtag("trigger");return this});jQuery(function(e){var t,n,r;r={};t=function(){return window.location.hash.replace("#","")};n={init:function(t){t!=null&&e.extend(r,t);return this},trigger:function(n){n==null&&(n=t());e.each(r,function(e,t){var r;r=new RegExp(e,"i");if(r.test(n))return t(n)});return this},set:function(e){window.location.hash=e;return this},bind:function(t,n){r[t]=n;e.fn.Hashtag("trigger");return this},unbind:function(e){r[e]=void 0;return this}};return e.fn.Hashtag=function(t){return n[t]!=null?n[t].apply(this,Array.prototype.slice.call(arguments,1)):typeof t=="object"||!t?n.init.apply(this,arguments):e.error("Method "+t+" does not exist on jQuery.Hashtag")}})}).call(this);